# Generated by Django 3.1 on 2021-02-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('remark', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
