# Generated by Django 3.1 on 2021-02-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullsite', '0003_upload_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_detail',
            name='filetype',
            field=models.CharField(default='', max_length=10),
        ),
    ]
